### Import track
POST http://localhost:7768/v1/track
Content-Type: multipart/form-data;boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="import_track.csv"

< ../src/test/resources/example/import_track.csv
--WebAppBoundary--

### Get track csv
GET http://localhost:7768/v1/track

### Get track csv by year
GET http://localhost:7768/v1/track/{{year}}

### Get track import csv example
GET http://localhost:7768/v1/track/example
