/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Oct 31 09:15:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.voucher.repository;

import com.gateweb.voucher.model.entity.InvoiceExternalEntity;
import java.util.Collection;
import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface InvoiceExternalRepository
    extends JpaRepository<InvoiceExternalEntity, Long>,
        JpaSpecificationExecutor<InvoiceExternalEntity> {

  // #1272 change limit 1
  @Query(
      value =
          "SELECT *\n"
              + "FROM invoice_external\n"
              + "WHERE owner in (:businessNos)\n"
              + "  AND year_month IN (:yearMonths)\n"
              + "  AND external_id > :externalId\n"
              + "ORDER BY external_id\n"
              + "limit :limit",
      nativeQuery = true)
  List<InvoiceExternalEntity> findDataBySeek(
      @Param("externalId") Long externalId,
      @Param("businessNos") Collection<String> businessNos,
      @Param("yearMonths") Collection<String> yearMonths,
      @Param("limit") Integer limit);
}
